### ISSUE TITLE
Render tweet location data

### ISSUE THREAD

**Issue by IgnatBeresnev** [ReckfulArchive/twitter-website#4]
Some tweets contain location data:

```
"location": {
    "place": "Amsterdam, The Netherlands",
    "countryCode": "NL"
},
```

This data should be used to render the place and the country flags in the tweet headers, probably on the right side of the tweet date.

**Comment by ryanc268** [comment]
Finished with 
https://github.com/ReckfulArchive/twitter-website/commit/8f400697cb39ad003536e9e2307a01c8fb587289
